"""Project OC DAP 4 file with config related variables and class."""


class CommandField:
    """Object with field with the string commands input."""

    ADD_PLAYER = "ap"
    BACK = "b"
    CREATE_NEXT_TURN = "cnt"
    EDIT_PLAYER = "ep"
    EDIT_TOURNAMENT = "eto"
    EDIT_TURN = "etu"
    TURNS = "etus"
    EXIT = "ex"
    GENERATE_PLAYERS = "gp"
    LOAD_PLAYERS = "lp"
    LOAD_TOURNAMENTS = "lt"
    MATCHES = "m"
    MATCH_RESULT = "mr"
    NEW = "n"
    PLAYERS = "p"
    PLAYERS_ALPHABETIC = "pa"
    PLAYERS_RANKING = "pr"
    RANKING = "r"
    SAVE_PLAYERS = "sp"
    SAVE_TOURNAMENTS = "st"
    TOURNAMENT_DATE = "tda"
    TOURNAMENT_LOCATION = "tl"
    TOURNAMENT_TURN_NUMBER = "ttu"
    TOURNAMENT_TIME = "tti"
    TOURNAMENT_DESCRIPTION = "tde"

    UNKNOWN = "uk"
    UPDATE_RANKING = "ur"
    TOURNAMENTS = "t"
